name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout (default: main)'
        required: false
        default: 'main'

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.WAXOM_SITE_WORKFLOW }}

      - name: Prepare files for artifacts
        run: |
          # Подготавливаем директории для артефактов
          mkdir -p artifacts/unchanged-files
          mkdir -p artifacts/js
          # Копируем неизменяемые файлы
          cp -r src/img artifacts/unchanged-files/ 2>/dev/null || true
          cp -r src/fonts artifacts/unchanged-files/ 2>/dev/null || true
          cp -r src/video artifacts/unchanged-files/ 2>/dev/null || true
          # Копируем JS файлы
          cp -r src/js artifacts/js/ 2>/dev/null || true
          # Копируем HTML и CSS файлы
          cp index.html artifacts/ 2>/dev/null || true
          if [ -f src/css/style.min.css ]; then
            cp src/css/style.min.css artifacts/ 2>/dev/null || true
          elif [ -f src/css/style.css ]; then
            cp src/css/style.css artifacts/ 2>/dev/null || true
          else
            echo "Neither style.min.css nor style.css found, failing"
            exit 1
          fi

      - name: Debug files before upload
        run: |
          echo "Files in artifacts directory:"
          find artifacts -type f -o -type d

      - name: Archive JS folder
        run: tar -czf artifacts/js-folder.tar.gz -C artifacts/js .

      - name: Upload unchanged files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: unchanged-files
          path: artifacts/unchanged-files/

      - name: Upload initial CSS files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: initial-css-files
          path: |
            artifacts/style.min.css
            artifacts/style.css

      - name: Upload initial HTML files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: initial-html-files
          path: artifacts/index.html

      - name: Upload JS archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: js-files
          path: artifacts/js-folder.tar.gz

  update-paths:
    runs-on: ubuntu-latest
    needs: copy-files
    steps:
      - name: Download initial HTML files
        uses: actions/download-artifact@v4
        with:
          name: initial-html-files
          path: .

      - name: Download initial CSS files
        uses: actions/download-artifact@v4
        with:
          name: initial-css-files
          path: .

      - name: Debug index.html before update
        run: |
          echo "index.html before update in update-paths:"
          cat index.html 2>/dev/null || echo "index.html not found"

      - name: Update HTML and CSS paths
        run: |
          # Определяем, какой CSS файл обновлять
          if [ -f style.min.css ]; then
            CSS_FILE="style.min.css"
            echo "Updating paths in style.min.css"
          elif [ -f style.css ]; then
            CSS_FILE="style.css"
            echo "Updating paths in style.css"
          else
            echo "Neither style.min.css nor style.css found, failing"
            exit 1
          fi
          # Обновляем тег <link> в index.html
          sed -i 's|<link[^>]*rel=["'\'']stylesheet["'\''][^>]*href=["'\'']\.\?\/*src\/css\/style\(.\min\)\?.css["'\'']|<link rel="stylesheet" href="style.css"|' index.html
          sed -i 's|<link[^>]*rel=["'\'']stylesheet["'\''][^>]*href=["'\'']\.\?\/*css\/style\(.\min\)\?.css["'\'']|<link rel="stylesheet" href="style.css"|' index.html
          # Удаляем префикс src/ из всех путей в index.html
          sed -i 's|\.\?\/*src\/||g' index.html
          # Отладка после обновления HTML
          echo "index.html after update in update-paths:"
          cat index.html 2>/dev/null || echo "index.html not found"
          # Обновляем пути в CSS
          echo "Before updating CSS paths in $CSS_FILE:"
          cat "$CSS_FILE"
          sed -i 's/@import'\''\.\.\/\([^'\'']*\)'\''/@import '\''\1'\''/g' "$CSS_FILE"
          echo "After updating @import paths in $CSS_FILE:"
          cat "$CSS_FILE"
          sed -i 's/url("\.\.\/\([^"]*\)"/url("\1"/g' "$CSS_FILE"
          echo "After updating url() paths in $CSS_FILE:"
          cat "$CSS_FILE"

      - name: Upload updated HTML files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: updated-html-files
          path: index.html

      - name: Upload updated CSS files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: updated-css-files
          path: |
            style.min.css
            style.css

  minify-css:
    runs-on: ubuntu-latest
    needs: update-paths
    steps:
      - name: Download updated CSS files
        uses: actions/download-artifact@v4
        with:
          name: updated-css-files
          path: .

      - name: Set up Node.js for CSS minification
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install uglifycss
        run: npm install uglifycss -g

      - name: Minify or rename CSS
        run: |
          if [ -f style.min.css ]; then
            echo "Found style.min.css, renaming to style.css"
            mv style.min.css style.css
          elif [ -f style.css ]; then
            echo "Found style.css, minifying"
            uglifycss style.css > style.min.css
            mv style.min.css style.css
            echo "Minified style.css"
          else
            echo "Neither style.min.css nor style.css found, failing"
            exit 1
          fi

      - name: Debug style.css after minification
        run: |
          echo "style.css after minification in minify-css:"
          cat style.css

      - name: Upload minified CSS as artifact
        uses: actions/upload-artifact@v4
        with:
          name: minified-css
          path: style.css

  minify-html:
    runs-on: ubuntu-latest
    needs: update-paths
    steps:
      - name: Download updated HTML files
        uses: actions/download-artifact@v4
        with:
          name: updated-html-files
          path: .

      - name: Debug index.html before minification
        run: |
          echo "index.html before minification in minify-html:"
          cat index.html 2>/dev/null || echo "index.html not found"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install html-minifier
        run: npm install html-minifier -g

      - name: Minify HTML
        run: html-minifier --collapse-whitespace --remove-comments index.html -o index.html

      - name: Debug index.html after minification
        run: |
          echo "index.html after minification in minify-html:"
          cat index.html 2>/dev/null || echo "index.html not found"

      - name: Upload minified HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: minified-html
          path: index.html

  minify-js:
    runs-on: ubuntu-latest
    needs: update-paths
    steps:
      - name: Download JS files
        uses: actions/download-artifact@v4
        with:
          name: js-files
          path: .

      - name: Extract and delete archive
        run: tar -xzf js-folder.tar.gz -C . && rm -f js-folder.tar.gz

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install uglify-js
        run: npm install uglify-js -g

      - name: Debug JS files before minification
        run: |
          echo "JS files found:"
          find js/ -type f -name "*.js" 2>/dev/null || echo "No JS files found"

      - name: Minify JS
        run: |
          if [ -d js ]; then
            find js/ -type f -name "*.js" -exec sh -c 'uglifyjs "{}" --mangle --compress > "{}.tmp" && mv "{}.tmp" "{}"' \;
          else
            echo "js/ directory not found, skipping minification"
          fi

      - name: Archive JS folder
        run: tar -czf js-folder.tar.gz js

      - name: Upload minified JS as artifact
        uses: actions/upload-artifact@v4
        with:
          name: minified-js
          path: js-folder.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: [minify-css, minify-html, minify-js]
    steps:
      - name: Checkout build branch
        uses: actions/checkout@v4
        with:
          ref: build
          token: ${{ secrets.WAXOM_SITE_WORKFLOW }}

      - name: Clean build branch
        run: |
          # Переключаемся на ветку build, если она существует, или создаём новую
          git checkout build || git checkout -b build
          # Подтягиваем изменения из origin/build, если ветка существует
          git pull origin build || true
          # Очищаем содержимое ветки
          git rm -r --ignore-unmatch '*'
          rm -rf .github
          find . -not -path './.git*' -not -name '.' -exec rm -rf {} \;
          # Убедимся, что рабочая директория пуста (кроме .git)
          echo "Working directory after cleanup:"
          ls -la

      - name: Download minified HTML
        uses: actions/download-artifact@v4
        with:
          name: minified-html
          path: .

      - name: Download minified CSS
        uses: actions/download-artifact@v4
        with:
          name: minified-css
          path: .

      - name: Download minified JS
        uses: actions/download-artifact@v4
        with:
          name: minified-js
          path: .

      - name: Download unchanged files
        uses: actions/download-artifact@v4
        with:
          name: unchanged-files
          path: .

      - name: Extract and delete JS archive
        run: tar -xzf js-folder.tar.gz -C . && rm -f js-folder.tar.gz

      - name: Debug final files before commit
        run: |
          echo "Final index.html before commit in deploy:"
          cat index.html 2>/dev/null || echo "index.html not found"
          echo "Final style.css before commit in deploy:"
          cat style.css 2>/dev/null || echo "style.css not found"
          echo "JS files after minification:"
          find js/ -type f -name "*.js" 2>/dev/null || echo "No JS files found"

      - name: Commit and push all changes
        run: |
          git config user.name "${{ secrets.USER_NAME }}"
          git config user.email "${{ secrets.USER_EMAIL }}"
          git add .
          git commit -m "Build from main: ${{ github.event.head_commit.message }} (SHA: ${{ github.sha }}) at $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || true
          git push origin build
